# Generated by Django 4.0.4 on 2022-04-21 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('start_point', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('start_altitude', models.IntegerField(verbose_name='Altitude au départ (m)')),
                ('min_altitude', models.IntegerField(verbose_name='Altitude minimale (m)')),
                ('max_altitude', models.IntegerField(verbose_name='Altitude maximale (m)')),
                ('cumulated_slope_up', models.IntegerField(verbose_name='Dénivelé positif cumulé (m)')),
                ('cumulated_slope_down', models.IntegerField(verbose_name='Dénivelé négatif cumulé (m)')),
                ('estimated_duration', models.PositiveIntegerField(verbose_name='Temps estimé (h)')),
                ('estimated_difficulty', models.PositiveSmallIntegerField(choices=[('1/5', 1), ('2/5', 2), ('3/5', 3), ('4/5', 4), ('5/5', 5)])),
            ],
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.PositiveIntegerField(verbose_name='Durée réelle (h)')),
                ('number_ppl', models.PositiveIntegerField(verbose_name='Nombre de participants (humains)')),
                ('group_xp', models.CharField(choices=[('Tous débutants', 0), ('Tous Expérimentés', 1), ('Mixte', 2)], max_length=20, verbose_name='Expérience des participants à la sortie')),
                ('weather', models.CharField(choices=[('Bonne', 0), ('Moyenne', 1), ('Mauvaise', 2)], max_length=8, verbose_name='Météo')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[('1/5', 1), ('2/5', 2), ('3/5', 3), ('4/5', 4), ('5/5', 5)], verbose_name='Difficulté ressentie')),
                ('itineraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraires.itineraire')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
